// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://disnqbvzhmrjytmadyzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpc25xYnZ6aG1yanl0bWFkeXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzI5MDUsImV4cCI6MjA3MzUwODkwNX0.f6Hx-k33-NncRPkannnEZpj3pml_p_pib-AnKt7miK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});